services:
  nginx:
    volumes:
      - ./nginx/nginx_dev.conf:/etc/nginx/nginx.conf:ro
  redis-commander:
    image: "rediscommander/redis-commander:latest"
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=
      - HTTP_PASSWORD=
    ports:
      - "8081:8081"
    depends_on:
      - "redis"
    networks:
      - "api.network"
